### ISSUE TITLE
Issue #0 - Wiki Home Page

### ISSUE THREAD

**Issue by keginzburg** [kcho760/OpenTableau#1]
# Wiki Home Page
- [X] Is the first page you see upon entering the wiki
- [X] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [X] Correctly formatted
  - [X] each wiki page is listed in bullet points
  - [X] all links route the correct page

## Comments

- [x] We do need to add our `Sample State` design doc when we can, but going forward, we should also have placeholder documents made for our `Backend Routes` and `Frontend Routes`.
- [x] Small fix as well, but let's add a placeholder Live Link which will get replaced when we Host on Render.
- **Solid work!**

**Comment by kcho760** [comment]
All issues fixed

**Comment by keginzburg** [comment]
Awesome work, looks great!
