### ISSUE TITLE
Issue #2 - Database Schema

### ISSUE THREAD

**Issue by keginzburg** [kcho760/OpenTableau#3]
# Database Schema
- [X] Contains correct datatypes
- [X] Contains appropriate constraints/details
  - [X] primary key
  - [X] not null
  - [X] unique
  - [X] indexed
  - [X] foreign key
- [X] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
  - [X] schema is written in a table format
  - [x] the table's name are lowercased, snake_cased and `back_ticked`
  - [X] the table header column names are bolded
  - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments

- [ ] OpenTable has an newer Auth system that relies on multi factor authentication. Instead, we're going to retrofit their Auth to what we know, which is a basic credential based system. With that in mind, we can store a `username`, but I recommend storing an `email` alone for signup and login with a password, and then maybe the user's `first_name` and `last_name`. We can always ask them for other information (i.e. `display_name`, `phone`, `dining_location`) later after they've signed up. **Let's talk about this before we jump into Auth this Friday.**
- [x] Should our `Reservations` also have an `reservation_end_time`? Or will all reservations keep a constant duration?
- [x] Are we sure we want to add a unique index to Restaurant `name`s? I'm sure I've encountered two restaurants with the same name. Maybe we store `zip_code` for Restaurants as well?
- [x] For Reviews, it looks like each Review provides an aggregate rating based on the Restaurant's `Food`, `Service`, `Ambience`, and `Overall`. Maybe we keep track of these float ratings in each Review?
- [ ] We have a Favorites table, but that might qualify as a Bonus for later. We can discuss as well.
- [x] Don't forget your `timestamps` for all tables!

**Comment by kcho760** [comment]
### Are we sure we want to add a unique index to Restaurant names? I'm sure I've encountered two restaurants with the same name. Maybe we store zip_code for Restaurants as well?

I've adjusted the reviews table to have 4 rating categories but set them to integers to keep them as whole numbers so I can create a "star" radio buttons on the review page. This also lets the reviews look cleaner on the restaurants page.  I have broken down the review categories on the restaurant page as well but let them be set as floats to provide a more accurate rating system.

### Should our Reservations also have an reservation_end_time? Or will all reservations keep a constant duration?
I'd like to keep it at constant duration for now. I'm not sure how difficult it would be to implement a reservation ending system and in the real world, reservations are generally plotted for an allotted time.


columns, tablenames, and foreign keys properly formatted

**Comment by keginzburg** [comment]
All of this is looking pretty solid.

One note is that your restaurants won't need to hold onto a rating in the backend. Instead, when fetching your restaurants, you can always pull a simple SQL query that AVG() all of their reviews ratings and then pass that along in your Jbuilder response. So we can nix those columns from our `Restaurants` table.

As long as we fix our `Users` table by removing a `username`, we should be good here.
